### ISSUE TITLE
Sittuyin variant support? [feature request]

### ISSUE THREAD

**Issue by teakado** [ianfab/Makruk-Stockfish#2]
I've opened this as a separate "issue" here just so it won't get lost among other discussions which are more relevant to the original thread. Thanks!

The official Sittuyin rule book is available online for free, on Scribd and on other sites that mirror Scribd. It was personally published to Scribd by the current president of the Burmese Chess Federation, Maung Maung Lwin. I just googled "How to Play Myanmar Traditional Chess by Maung Maung 
Lwin."

**Comment by ianfab** [comment]
I recently created a new Stockfish fork "[Fairy-Stockfish](https://github.com/ianfab/Fairy-Stockfish)" with the aim of making it easier to add/configure new variants, especially variants with fairy pieces. Therefore, I do not consider any more to implement new variants in this fork (but will still try to maintain this dedicated makruk engine, since its playing strength is higher), and will rather try to add them to the new fork. So I am closing this issue in favor of https://github.com/ianfab/Fairy-Stockfish/issues/1.

ASEAN chess is already supported in the new fork. I also consider ouk and sittuyin, but due to some of their special rules, other variants (e.g., drop variants like crazyhouse, which is anyway a prerequisite for sittuyin) have higher priority for me at the moment. The project is still in an experimental stage and for now I am completely focusing on implementing rules without improving playing strength, so do not expect it to play too well yet.

**Comment by ianfab** [comment]
FYI, Sittuyin is implemented in [Fairy-Stockfish](https://github.com/ianfab/Fairy-Stockfish) now.

**Comment by thaichessswinboard** [comment]
http://hgm.nubati.net/WinBoard-AA.zip can play stockfish too. rename
stockfish 9 to the same foloder it will load stockfish to play on winboard
and then go to file and new variants it will work. if computer go to slow
go to general and then don't tick on animation both. it will fast more than
use animation. Enjoy. and one other thing for makruk variants don't use
syzygy because when it move more than 50 move rules it will move wrong
position becuase it think program will draw or game must stop but for
Makruk counting can use or not use after no pawn that why it not the same
likes chess game thinking. I hope you understand and for the rule of makruk
you from position.h  you can include position.h to endgame.cpp it will work
and no the rules more but it must plus two king and another pieces on board
it will correct rules and make it progress more than old source code. it
You can make it perferfect it will be good for Makruk fan around the world.
many thanks to read my email.

**Comment by thaichessswinboard** [comment]
[image: image.png]

it working this is pictures and some of example game run on winboard-AA
and I also edit some of old source code by copy position.h from Your
original source code to fairy-makruk source code for test the rules and
compiles it works. But need to resolve some hard problem of Makruk hard
position and I will explain to you  more. Thanks for do variants Makruk for
people and publish. You very kind of programmer. If program less Bugs in
the future can be good for people around the world or another Galaxy. I
Enjoy very much. Thanks for read my Email again.


[Event "Computer Chess Game"]
[Site "PCST"]
[Date "2018.11.04"]
[Round "-"]
[White "Stockfish 221018 64 (UCI2WB)"]
[Black "Stockfish 221018 64 (UCI2WB)"]
[Result "1/2-1/2"]
[TimeControl "400/120"]
[Variant "makruk"]
[Annotator "1. +0.07   1... -0.12"]

1. Nd2 Nd7 2. f4 Ne7 3. Ngf3 Kf7 4. Ke2 Kg7 5. Kf2 e5 6. Sc2 exf4 7. exf4
Sf7 8. Kg2 Mc7 9. Mf2 Sb7 10. Se2 a5 11. Nf1 f5 12. Ne3 Nf6 13. Rhe1 Rhe8
14. c4 d5 15. Rab1 Md6 16. b4 axb4 17. axb4 dxc4 18. dxc4 b5 19. Rbd1 Mc7
20. Sed3 Rad8 21. c5 Ned5 22. Nxd5 Nxd5 23. Sb3 Rxe1 24. Rxe1 Mb8 25. Sd4
Nc7 26. g4 Sf6 27. Sc2 fxg4 28. hxg4 h5 29. gxh5 gxh5 30. Mg3 Sf5 31. Se5
Nd5 32. Nd4 Kg6 33. Sb3 Mc7 34. Kf1 Rf8 35. Kf2 h4 36. Mxh4 Sxf4 37. Rg1+
Kh7 38. Ne6 Rf5 39. Sxf4 Nxf4 40. Nxf4 Rxf4+ 41. Kg3 Re4 42. Rf1 Kg6 43.
Rf4 Re3+ 44. Rf3 Re4 45. Rf8 Kg7 46. Rf4 Re2 47. Rf2 Re4 48. Rf4 Re2 49.
Rf2 Re4 50. Rf4
{XBoard adjudication: repetition draw} 1/2-1/2

Regard
PCST.
