### ISSUE TITLE
KBQK from behind Queen or Med direct to the conner.

### ISSUE THREAD

**Issue by Mstpcst** [ianfab/Makruk-Stockfish#4]
how to solve the problem KBQK from behind the same conner with Queen or (Med) 

[Event "¡Å·Õè 70"]
[Site ""]
[Date ""]
[Round ""]
[White "   14 ·ÕË¹Õ  15 ·ÕäÅè"]
[Black ""]
[Result "1-0"]
[Variant "makruk"]
[CurrentMove "0"]
[FEN "8/8/8/8/6M1/5S2/5K2/7k w 0 1"]
[SetUp "1"]

{--------------
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . M .
. . . . . S . .
. . . . . K . .
. . . . . . . k
white to play
--------------}
1. Sg2+ Kh2 2. Sf1 Kh1 3. Ke3 Kg1 4. Ke2 Kh2 5. Kf3 Kg1 6. Se2 Kh1 7. Kg3
Kg1 8. Mf3 Kh1 9. Kf2 Kh2 10. Mg4 Kh1 11. Sf3 Kh2 12. Sf4 Kh1 13. Mf3 Kh2
14. Sg3+ Kh1 15. Mg2#
{++} 1-0

**Comment by ianfab** [comment]
@Mstpcst 
I have done some testing on this position with the current version of the master branch, and the behavior seems to be fine to me:
- At short time controls (e.g., 1-10s for the rest of the game starting from this position), it is not able to checkmate the king in the "wrong" corner, so it drives the king to the other side of the board where it is able to deliver checkmate (within 20-40 moves depending on time control).
- At long time controls (e.g. 1 min for the rest of the game), it finds the mate in 15, keeps the king in the corner, and plays the shortest possible sequence until checkmate.

Trying to force it to always keep the king in the corner (as in #5) proved to be ineffective, because Stockfish then is not able to checkmate with KBQK at short time controls.

Since I do not really see an issue here, I am closing this, but feel free to reopen it if you encounter issues in this endgame again.
